# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\noaa-afsc-mace\CamtrawlEchogram\ui\progressDlg.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_progressDlg(object):
    def setupUi(self, progressDlg):
        progressDlg.setObjectName("progressDlg")
        progressDlg.resize(600, 104)
        self.verticalLayout = QtWidgets.QVBoxLayout(progressDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=progressDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(parent=progressDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbCancel = QtWidgets.QPushButton(parent=progressDlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pbCancel.setFont(font)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(progressDlg)
        QtCore.QMetaObject.connectSlotsByName(progressDlg)

    def retranslateUi(self, progressDlg):
        _translate = QtCore.QCoreApplication.translate
        progressDlg.setWindowTitle(_translate("progressDlg", "Progress"))
        self.label.setText(_translate("progressDlg", "TextLabel"))
        self.pbCancel.setText(_translate("progressDlg", "Cancel Export"))
